// the battery's two lists, kept apart from run.mjs so `node run.mjs --list` can print them without
// loading a target or reaching a server

// a suite that had nothing it was allowed to do on this target
export const EXIT_SKIPPED = 3

export const WIPE_CYCLE = ['e2e-history', 'e2e', 'e2e-editor', 'e2e-widgets', 'e2e-settings', 'e2e-importer']

export const SAFE_SUITES = [
  'e2e-button',
  'e2e-corners',
  'e2e-launch',
  'e2e-https',
  'e2e-editfix',
  'e2e-copypaste',
  'e2e-lassoarea',
  'e2e-dashmgmt',
  'e2e-place',
  'e2e-breakpoints',
  'e2e-generate',
  'e2e-newfeat',
  'e2e-sidebar',
  'e2e-lock',
  'e2e-i18n',
  'e2e-backgrounds',
  'e2e-partial',
  'e2e-gallery',
  'e2e-templates',
  'e2e-icons',
  'e2e-iconpacks',
  'e2e-hue',
  'e2e-colorpower',
  'e2e-fade',
  'e2e-livedrag',
  'e2e-stepper',
  'e2e-battery',
  'e2e-value',
  'e2e-slider',
  'e2e-thermostat',
  'e2e-log',
  'e2e-clocktime',
  'e2e-cmdfail',
  'e2e-charts',
  'e2e-chartagg',
  'e2e-gauge',
  'e2e-camera',
  'e2e-resizefix',
  'e2e-responsive',
  'e2e-portrait',
  'e2e-textscale',
  'e2e-textsize',
  'e2e-labelalign',
  'e2e-themecss',
  'e2e-themerules',
  'e2e-ember',
  'e2e-lcd',
  'e2e-ops',
  'e2e-weather',
  'e2e-assembly',
  'e2e-floorplan',
  'e2e-panels',
  'e2e-runfit',
  'e2e-detail',
  'e2e-kiosk',
  'e2e-audit2',
  'e2e-audit3',
  'e2e-voiceaudio',
  'e2e-timeclock',
  'e2e-stateicons',
  'e2e-signin',
  'e2e-proxyauth',
  'e2e-multitab',
]
