/**
 * Base icon names of the openHAB 'classic' icon set (state-suffix variants collapsed;
 * the server picks the right variant from the ?state= parameter).
 */
export const CLASSIC_ICONS: string[] = [
  'alarm', 'attic', 'baby_1', 'baby_2', 'baby_3', 'baby_4',
  'baby_5', 'baby_6', 'bath', 'battery', 'batterylevel', 'bedroom',
  'bedroom_blue', 'bedroom_orange', 'bedroom_red', 'blinds', 'bluetooth', 'boy_1',
  'boy_2', 'boy_3', 'boy_4', 'boy_5', 'boy_6', 'calendar',
  'camera', 'carbondioxide', 'cellar', 'chart', 'cinema', 'cinemascreen',
  'cistern', 'climate', 'colorlight', 'colorpicker', 'colorwheel', 'contact',
  'corridor', 'door', 'dryer', 'energy', 'error', 'fan',
  'fan_box', 'fan_ceiling', 'faucet', 'fire', 'firstfloor', 'flow',
  'flowpipe', 'frontdoor', 'garage', 'garage_detached', 'garage_detached_selected', 'garagedoor',
  'garden', 'gas', 'girl_1', 'girl_2', 'girl_3', 'girl_4',
  'girl_5', 'girl_6', 'greenhouse', 'groundfloor', 'group', 'heating',
  'house', 'humidity', 'incline', 'input', 'keyring', 'kitchen',
  'lawnmower', 'light', 'lightbulb', 'line', 'line-decline', 'line-incline',
  'line-stagnation', 'lock', 'lowbattery', 'man_1', 'man_2', 'man_3',
  'man_4', 'man_5', 'man_6', 'mediacontrol', 'microphone', 'moon',
  'motion', 'movecontrol', 'network', 'niveau', 'none', 'office',
  'oil', 'outdoorlight', 'pantry', 'parents', 'parents_1_1', 'parents_1_2',
  'parents_1_3', 'parents_1_4', 'parents_1_5', 'parents_1_6', 'parents_2_1', 'parents_2_2',
  'parents_2_3', 'parents_2_4', 'parents_2_5', 'parents_2_6', 'parents_3_1', 'parents_3_2',
  'parents_3_3', 'parents_3_4', 'parents_3_5', 'parents_3_6', 'parents_4_1', 'parents_4_2',
  'parents_4_3', 'parents_4_4', 'parents_4_5', 'parents_4_6', 'parents_5_1', 'parents_5_2',
  'parents_5_3', 'parents_5_4', 'parents_5_5', 'parents_5_6', 'parents_6_1', 'parents_6_2',
  'parents_6_3', 'parents_6_4', 'parents_6_5', 'parents_6_6', 'party', 'pie',
  'piggybank', 'player', 'poweroutlet', 'poweroutlet_au', 'poweroutlet_eu', 'poweroutlet_uk',
  'poweroutlet_us', 'presence', 'pressure', 'price', 'projector', 'pump',
  'qualityofservice', 'radiator', 'rain', 'receiver', 'recorder', 'returnpipe',
  'rgb', 'rollershutter', 'screen', 'settings', 'sewerage', 'shield',
  'siren', 'slider', 'smiley', 'smoke', 'snow', 'sofa',
  'softener', 'solarplant', 'soundvolume', 'soundvolume_mute', 'status', 'suitcase',
  'sun', 'sun_clouds', 'sunrise', 'sunset', 'switch', 'temperature',
  'temperature_cold', 'temperature_hot', 'terrace', 'text', 'time', 'toilet',
  'vacation', 'video', 'wallswitch', 'wardrobe', 'washingmachine', 'washingmachine_2',
  'water', 'whitegood', 'wind', 'window', 'woman_1', 'woman_2',
  'woman_3', 'woman_4', 'woman_5', 'woman_6', 'zoom',
]
